### ISSUE TITLE
Create tasks.ini backup

### ISSUE THREAD

**Issue by error401de** [error401de/recurring-tasks#16]
To be resilient against accidentally deletion of config.ini, an automatic backup on each run would be nice.

- Create new script backup.py for better overview and import it to checkTasks.py
- Create backup on each run in folder "backup"
- Filename "tasks.ini.backup.[timestamp]
- Backup retention: Define new section [backup] with setting "Retention = 3" in config.ini - Oldest backups higher than the retention setting should be deleted on each run
- add "backup" folder to .gitignore
- describe functionality in README.md

**Comment by haydenccarroll** [comment]
Can I work on this one?

**Comment by error401de** [comment]
Yes!
I assigned the issue to you. Thanks in advance!

**Comment by error401de** [comment]
Hint: Just updated issue: `- Filename "tasks.ini.backup.[timestamp]`
(was config.ini, which was wrong)

**Comment by haydenccarroll** [comment]
Okay, to be clear you want a new section in config.ini that defines backup behavior (retention) for tasks.ini?

**Comment by error401de** [comment]
Yes, exactly.

**Comment by haydenccarroll** [comment]
@error401de Just submitted a PR. While working on the PR, I noticed that the program does not work if the user runs it from a different directory. I will submit an Issue and fix this. I just wasn't sure if it's ok to do multiple things in a single PR. I am still new to contributing to open source projects :)

**Comment by error401de** [comment]
@haydenccarroll Awesome, thanks!
There is a little issue in the PR, i will request a change in there.
Thanks for noticing the directory issue and taking care, much appreciated! Additional issue + PR is perfect :)
