### ISSUE TITLE
Validation of task configurations

### ISSUE THREAD

**Issue by error401de** [error401de/recurring-tasks#4]
Currently the configurations in tasks.ini are not validated, so wrong values could crash the script.
Errors in config should result into a warning via email.

**Comment by Paola351** [comment]
What types of check do you want me to do?

**Comment by error401de** [comment]
"Type" should only contain "daily", "weekly", "monthly", "yearly" or "free"
"Weekday" should only contain values out of array "daysOfTheWeek" in checkTasks.py
"Day" should only contain integers between 1 and 31
"Month" should only contain values out of array "monthsOfTheYear" in checkTasks.py

As it's possible for most values to provide multiple ones, one should iterate over all values.
The opposite for "yearly" tasks: This is a specific date and it should be checked that only one date is configured.

Do you want me to assign the issue to you @Paola351 ? :)

**Comment by Paola351** [comment]
yes please :D

**Comment by Paola351** [comment]
done :D
